---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deployment
 labels:
     app: my-app
     type: front-end 	
spec:
  template:
    metadata: my-pod
     name:
     labels:
        app: my-app
        type: front-end
    spec: 
      containers: 
      - name: c001
        image: nginx
  replicas: 6
  selector:
     matchLabels:
        type: front-end              
	   
