apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: c001
    image: nginx
    volumeMounts:
    - name: nginx-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-storage
    hostPath:
      # directory location on host
      path: /var/log/nginx
