apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: c001
    image: nginx
    volumeMounts:
    - name: nginx-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-storage
    hostPath:
      path: /var/www/nginx/html
