apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: c001
    image: nginx
    volumeMounts:
    - name: nginx-storage-local
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-storage-local
    hostPath:
      path: /var/www/nginx/html
