---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: nginx
    name: nginx
  - command:
    - "sh"
    - "-c"
    - "tail n+1 /var/log/legacy-app.log"
    image: busybox
    name: busybox
    volumeMounts:
    - name: logs
      mountPath: /var/log
  volumes:
  - name: logs
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
