---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar
  name: legacy-app
spec:
  containers:
  - name: nginx
    image: nginx
  - command: ["/bin/sh"]
    args: ["-c", "tail -n+1 /var/log/legacy-app.log"]
    image: busybox
    name: sidecar
    volumeMounts:
    - mountPath: "/var/log"
      name: pv-storage
  volumes:
  - name: pv-storage
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
