---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar
  name: sidecar
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  - args: ["/bin/sh", "-c", "tail -n+1 -f /var/log/nginx/*.log"]
    image: busybox
    name: sidecar
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  volumes:
  - name: logs
    emptyDir: {}

