apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
     app: my-app
     type: front-end 	
spec: 
   containers: 
   - name: c001
     image: nginx
     ports:
     -  containerPort: 80  
   - name: c002
     image: redis
     ports:
     -  containerPort: 6379
