apiVersion: apps/v1
kind: pod
metadata:
 name: my-pod
 labels:
     app: myapp
     type: front-end 	
 spec: 
   containers: 
   - name: c001
     image: nginx
     ports:
     -  containerPort: 80      
	   
